<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{4ed37e00-bb03-4a14-80ff-f38f7977a9e4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//]]></ST>
    </Implementation>
    <Action Name="ACT_deneme" Id="{6305d8ff-c27a-49cd-8dfc-08fba6290b48}">
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="MAIN.ACT_deneme">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>